# Generated by Django 3.2.5 on 2021-07-17 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAdvertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('baseadvertising_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advertiser_management.baseadvertising')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('advertiser_management.baseadvertising', models.Model),
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('baseadvertising_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advertiser_management.baseadvertising')),
                ('title', models.CharField(max_length=100)),
                ('imgURL', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('theAdvertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser_management.advertiser')),
            ],
            bases=('advertiser_management.baseadvertising', models.Model),
        ),
    ]
