# Generated by Django 3.2.5 on 2021-07-16 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAdvertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_clicks', models.IntegerField()),
                ('_views', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('baseadvertising_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advertiser_management.baseadvertising')),
                ('_title', models.CharField(max_length=100)),
                ('_imgURL', models.CharField(max_length=100)),
                ('_link', models.CharField(max_length=100)),
            ],
            bases=('advertiser_management.baseadvertising', models.Model),
        ),
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('baseadvertising_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advertiser_management.baseadvertising')),
                ('_name', models.CharField(max_length=100)),
                ('_totalclicks', models.IntegerField()),
            ],
            bases=('advertiser_management.baseadvertising', models.Model),
        ),
    ]
