# Generated by Django 3.2.5 on 2021-07-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0004_ad_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='ipaddress',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='view',
            name='ipaddress',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
