# Generated by Django 3.2.5 on 2021-07-22 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0006_auto_20210722_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertiser',
            name='highlighted',
        ),
        migrations.RemoveField(
            model_name='advertiser',
            name='owner',
        ),
    ]
