# Generated by Django 3.2.5 on 2021-07-22 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0007_auto_20210722_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='highlighted',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='owner',
        ),
    ]
