# Generated by Django 3.2.5 on 2021-07-22 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertiser_management', '0009_auto_20210722_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='highlighted',
        ),
        migrations.AddField(
            model_name='advertiser',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisers', to=settings.AUTH_USER_MODEL),
        ),
    ]
