# Generated by Django 3.2.5 on 2021-07-24 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0010_auto_20210722_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickViewInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_num', models.IntegerField()),
                ('view_num', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyClickViewInfo',
            fields=[
                ('clickviewinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advertiser_management.clickviewinfo')),
            ],
            bases=('advertiser_management.clickviewinfo',),
        ),
        migrations.CreateModel(
            name='HourlyClickViewInfo',
            fields=[
                ('clickviewinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advertiser_management.clickviewinfo')),
            ],
            bases=('advertiser_management.clickviewinfo',),
        ),
    ]
